CREATE TABLE SPYDIVI(
	TRADEDATE DATE NULL,
	DIVIAMOUNT DECIMAL(12, 6) NULL
)

CREATE TABLE SPYPRICING(
	TRADEDATE DATE NULL,
	OPENED DECIMAL(12, 6) NULL,
	HIGH DECIMAL(12, 6) NULL,
	LOW DECIMAL(12, 6) NULL,
	CLOSED DECIMAL(12, 6) NULL,
	VOLUME BIGINT NULL,
	TIMESTEP INT NULL
)

CREATE TABLE SPYKEYWORDS (
	date_value TIMESTAMP NULL,
	Trump INT NULL,
	Presidend INT NULL,
	Debt INT NULL,
	Loan INT NULL,
	Mortgage INT NULL,
	Utilities INT NULL,
	Dow_Jones INT NULL,
	Stock_market INT NULL,
	Trading INT NULL,
	Dog INT NULL,
	Spy INT NULL,
	S&P INT NULL,
	Economy INT NULL,
	Election INT NULL,
	Apple INT NULL,
	Politics INT NULL,
	Unemployment INT NULL,
	Interest_rates INT NULL,
	Fed_funds_rate INT NULL
)

CREATE TABLE SPYPRICING_IEX(
	TRADEDATE DATE NULL,
	RECEIVETIME TIMESTAMP NULL,
	HIGH DECIMAL(12, 6) NULL,
	LOW DECIMAL(12, 6) NULL,
	AVERAGE DECIMAL(12, 6) NULL,
	VOLUME INT NULL,
	NOTIONAL INT NULL,
	NUMBEROFTRADES INT NULL,
	MARKETHIGH DECIMAL(12, 6) NULL,
	MARKETLOW DECIMAL(12, 6) NULL,
	MARKETAVERAGE DECIMAL(12, 6) NULL,
	MARKETVOLUME INT NULL,
	MARKETNUMBEROFTRADES INT NULL,
	OPEN DECIMAL(12, 6) NULL,
	CLOSE DECIMAL(12, 6) NULL,
	MARKETOPEN DECIMAL(12, 6) NULL,
	MARKETCLOSE DECIMAL(12, 6) NULL,
	CHANGEOVERTIME DECIMAL(12, 6) NULL,
	MARKETCHANGEOVERTIME DECIMAL(12, 6) NULL
)

CREATE TABLE SpyInformation.BITCOINKEYWORDS(
	date_values TIMESTAMP,
	Bitcoin INT,
	Altcoin INT,
	Ethereum INT,
	BTC	INT,
	ETH INT,
	Crypto INT,
	Cryptocurrency INT,
	Currency INT
);

CREATE TABLE SPY.SPYKEYWORDS (
  date_values timestamp NOT NULL,
  Trump int DEFAULT NULL,
  President int DEFAULT NULL,
  Debt int DEFAULT NULL,
  Loan int DEFAULT NULL,
  Mortgage int DEFAULT NULL,
  Utilities int DEFAULT NULL,
  Dow_Jones int DEFAULT NULL,
  Stock_market int DEFAULT NULL,
  Trading int DEFAULT NULL,
  Dog int DEFAULT NULL,
  Spy int DEFAULT NULL,
  SandP int DEFAULT NULL,
  Economy int DEFAULT NULL,
  Election int DEFAULT NULL,
  Apple int DEFAULT NULL,
  Politics int DEFAULT NULL,
  Unemployment int DEFAULT NULL,
  Interest_rates int DEFAULT NULL,
  Fed_funds_rate int DEFAULT NULL
);

CREATE TABLE BITCOIN.BITCOINPRICEINDEX (
	RECEIVETIME TIMESTAMP,
	USD_BTC DECIMAL(8, 4),
	GBP_BTC DECIMAL(8, 4),
	EUR_BTC DECIMAL(8, 4)
);

CREATE TABLE BITCOIN.BITCOINKEYWORDS (
  date_values timestamp NOT NULL,
  Bitcoin int DEFAULT NULL,
  Altcoin int DEFAULT NULL,
  Ethereum int DEFAULT NULL,
  BTC int DEFAULT NULL,
  ETH int DEFAULT NULL,
  Crypto int DEFAULT NULL,
  Cryptocurrency int DEFAULT NULL,
  Currency int DEFAULT NULL
);